matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libgmp-dev
        - libmpfr-dev
        - libmpc-dev
        - verilator
        - ngspice
    env:
    - CC=gcc-7
    - CXX=g++-7
  - os: osx
    osx_image: xcode10.2
    addons:
      homebrew:
        packages:
          - verilator
          - ngspice

# python managed by conda until 3.7 available
# python:
# - '3.6'

install:
# install conda for py 3.7
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
  else
    # install conda for py 3.7
    wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  fi
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=3.7.3
- source activate test-env
- conda install pip
# End install conda
- curl -s -L https://github.com/rdaly525/coreir/releases/latest | grep "href.*coreir-${TRAVIS_OS_NAME}.tar.gz" | cut -d \" -f 2 | xargs -I {} wget https://github.com"{}"
- mkdir coreir_release;
- tar -xf coreir-${TRAVIS_OS_NAME}.tar.gz -C coreir_release --strip-components 1;
- cd coreir_release && sudo make install && cd ..
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # avoid strange libjpeg error (see https://github.com/sgrif/pq-sys/issues/1
    # for some more info)
    export DYLD_LIBRARY_PATH=/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/:/usr/local/lib:$DYLD_LIBRARY_PATH
  fi
- pip install pytest-cov pytest-codestyle
- pip install mantle  # for tests.common
- pip install -e .
# Begin setup CoSA dependencies
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pysmt-install --msat --confirm-agreement
  fi
- pysmt-install --z3 --confirm-agreement
- export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.7:${PYTHONPATH}"
- export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.7:${LD_LIBRARY_PATH}"
- pysmt-install --check
# End setup CoSA dependencies

script:
- pytest --cov fault --codestyle fault -v --cov-report term-missing tests
deploy:
  provider: script
  script: /bin/bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
